name = "deckmasters-astro"
account_id = "e1ef23a482d710064edcfdf77f1324c1"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
# PUBLIC_TURNSTILE_SITE_KEY should be set in the Cloudflare Dashboard



[[kv_namespaces]]
binding = "SESSION"
id = "220c7da78bbb4419b978f3276af98d47"
