name = "deckmasters-astro"
account_id = "e1ef23a482d710064edcfdf77f1324c1"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
PUBLIC_TURNSTILE_SITE_KEY = "0x4AAAAAACibBjpNvEOAYivu"

[[routes]]
pattern = "decks.stokeleads.com"
custom_domain = true

[[kv_namespaces]]
binding = "SESSION"
id = "220c7da78bbb4419b978f3276af98d47"

[images]
binding = "CF_IMAGES"
